# Generated by Django 4.2.7 on 2025-07-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
    ]
